[WIP]Add innerEvent for carrying events in the functions-framework
OpenFunction/functions-framework-go pull request #33
Opened 2022-02-21 13:38 UTC by tpiperatgod

Signed-off-by: laminar <fangtian@kubesphere.io>

2022-02-21 15:04 UTC, benjaminhuo requested changes

2022-02-21 15:13 UTC, tpiperatgod commented on context/innerevent.go
> +	return inner.data.Metadata
It should be necessary

2022-02-22 02:18 UTC, benjaminhuo commented on context/context.go
> +func (ctx *FunctionContext) setEvent(name string, be *common.BindingEvent, te *common.TopicEvent, ce *cloudevents.Event, ie InnerEvent) {
it's ok for interface

2022-02-22 12:22 UTC, benjaminhuo commented on context/context.go
> +	needWrapComponents = []string{
needWrapComponents => bindingQueueComponents
and it shouldn't be an array, should be a map to speed up searching : map[string]bool

2022-02-22 14:18 UTC, benjaminhuo requested changes

2022-02-22 14:27 UTC, tpiperatgod commented on context/context.go
> +func needWrap(t string) bool {
ok

2022-02-23 01:53 UTC, benjaminhuo approved these changes

2022-02-23 01:53 UTC, merged